version: 2 
jobs:
  build:
    docker:      
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout     
      - run:
          name: Make jar file
          command: |
            mvn package
       

      - run:
          name: Run jar file        
          command: |
            
